const products = [
    {
      id: 1,
      imageUrl: 'https://cdn.pixabay.com/photo/2016/12/06/09/31/blank-1886008_1280.png',
      title: 'Product 1',
      description: 'This is the first product.',
      color: 'Red',
      categories: ['Electronics', 'Sport', 'Fishing'],
      keywords: ['electronics', 'gadget', 'tech'],
      author: "Ondrej",
      state: 'approved',
      commissionState: 'filled',
      commission: '50 CZK',
      date: '2022-02-2',
    },
    {
      id: 2,
      imageUrl: 'https://cdn.pixabay.com/photo/2016/12/06/09/31/blank-1886013_1280.png',
      title: 'Product 2',
      description: 'A stylish accessory for any occasion.',
      color: 'White',
      categories: ['Fashion'],
      keywords: ['fashion', 'accessory', 'style'],
      author: "Ondrej",
      state: 'waiting',
      commissionState: 'filled',
      commission: '50 CZK',
      date: '2022-02-2',
    },
    {
      id: 3,
      imageUrl: 'https://cdn.pixabay.com/photo/2012/04/26/14/33/t-shirt-42654_1280.png',
      title: 'Product 3',
      description: 'Versatile and durable.',
      color: 'Blue',
      categories: ['Home & Kitchen'],
      keywords: ['home', 'kitchen', 'utility'],
      author: "Ondrej",
      state: 'approved',
      commissionState: 'filled',
      commission: '50 CZK',
      date: '2022-02-2',
    },
    {
      id: 4,
      imageUrl: 'https://cdn.pixabay.com/photo/2012/04/26/14/33/t-shirt-42654_1280.png',
      title: 'Product 4',
      description: 'Versatile and durable.',
      color: 'Blue',
      categories: ['Home & Kitchen'],
      keywords: ['home', 'kitchen', 'utility'],
      author: "Ondrej",
      state: 'waiting',
      commissionState: 'filled',
      commission: '50 CZK',
      date: '2022-02-2',
    },
    {
      id: 5,
      imageUrl: 'https://cdn.pixabay.com/photo/2016/12/06/09/31/blank-1886008_1280.png',
      title: 'Product 5',
      description: 'A stylish accessory for any occasion.',
      color: 'White',
      categories: ['Fashion'],
      keywords: ['fashion', 'accessory', 'style'],
      author: "Ondrej",
      state: 'waiting',
      commissionState: 'filled',
      commission: '50 CZK',
      date: '2022-02-2',
    },
    // Add more products here if needed
  ];
  
export default products;